name: SonarCloud Analysis

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    name: Build and analyze on SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download mssql-jdbc-12.10.1 artifact
        uses: actions/download-artifact@v4
        with:
          name: mssql-jdbc-12.10.1

      - name: Install mssql-jdbc-12.10.1.jre11.jar to local Maven repo
        run: |
          mvn install:install-file \
            -Dfile=mssql-jdbc-12.10.1/mssql-jdbc-12.10.1.jre11.jar \
            -DgroupId=com.microsoft.sqlserver \
            -DartifactId=mssql-jdbc \
            -Dversion=12.10.1.jre11 \
            -Dpackaging=jar

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and test with Maven
        run: mvn -B clean verify

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B verify sonar:sonar \
            -Dsonar.projectKey=prathameshakole_student-life-assistance \
            -Dsonar.organization=studentlife \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN 