name: Upload mssql-jdbc JAR

on:
  workflow_dispatch:

jobs:
  upload-jar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload mssql-jdbc-12.10.1.jre11.jar as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mssql-jdbc-12.10.1
          path: student-app-backend/src/main/mssql-jdbc-12.10.1.jre11.jar 
